Release 2024.3.1
conda-forge/nebari-dask-feedstock pull request #14
Opened 2024-03-05 20:51 UTC by marcelovilla

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-03-05 20:52 UTC, marcelovilla commented
@conda-forge-admin, please rerender

2024-03-11 13:58 UTC, dcmcand requested changes

2024-03-11 13:58 UTC, dcmcand commented on recipe/meta.yaml
>      - iameskild
We should probably remove Eskild here

2024-03-11 14:40 UTC, dcmcand commented
@conda-forge-admin, please rerender

2024-03-11 14:41 UTC, dcmcand approved these changes

2024-03-11 14:57 UTC, merged